version: "3"

services:
  obatin-db:
    image: yassarnaufal/obatin:db-develop
    restart: "always"
    ports:
      - "9000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  obatin-be:
    image: yassarnaufal/obatin:be-develop
    network_mode: host
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      obatin-db:
        condition: service_healthy
    restart: "always"
    logging:
      driver: "json-file"

  obatin-be-express:
    image: yassarnaufal/obatin:be-express-develop
    network_mode: host
    env_file:
      - ./proxy/.env
    ports:
      - "8081:8081"
    restart: "always"

  obatin-fe:
    image: yassarnaufal/obatin:fe-develop
    network_mode: host
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      obatin-be:
        condition: service_started
    restart: "always"

  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      obatin-be:
        condition: service_started
      obatin-fe:
        condition: service_started
    restart: "always"
