package appconstant

const (
	EndpointPing                     = "/ping"
	EndpointLogin                    = "/auth/login"
	EndpointRegisterDoctor           = "/auth/register/doctors"
	EndpointRegisterUser             = "/auth/register/users"
	EndpointVerify                   = "/auth/verify"
	EndpointSendVerifyToEmail        = "/auth/verify/mail"
	EndpointGetProductsList          = "/shop/products"
	EndpointUpdatePassword           = "/auth/update-password"
	EndpointApproval                 = "/approve/:authentication_id"
	EndPointAllCategories            = "/shop/categories"
	EndpointUpdateCategory           = "/shop/categories/:category_slug"
	EndpointForgotPassword           = "/auth/forgot-password"
	EndpointGetDoctorSpecialization  = "/doctor-specializations"
	EndpointGetDoctorPendingApproval = "/doctor-pending-approval"
	EndpointGetProductDetail         = "/shop/products/:product_slug"
	EndpointUserDetails              = "/users/:authentication_id"
	EndpointGetDoctorList            = "/doctors"
	EndpointGetDoctorDetail          = "/doctors/:doctor_id"
	EndpointGetDoctorDetailUser      = "/public/doctors/:doctor_id"
	EndpointRefreshToken             = "/auth/refresh-token"
	EndpointRegisterPartner          = "/auth/register/partners"
	EndpointGetPartnerList           = "/partners"
	EndpointUpdatePartner            = "/partners/:id"
	EndpointGetPartnerById           = "/partners/:id"
	EndpointUserAddress              = "/users/:authentication_id/addresses"
	EndpointUserAddressDetails       = "/users/:authentication_id/addresses/:address_id"
)
