package appconstant

const (
	ResponsePongMsg                       = "pong"
	ResponseNotfoundMsg                   = "not found"
	ResponseRegisterMsg                   = "email registered successfully"
	ResponseLoginMsg                      = "successfully logged in"
	ResponseForgotPasswordMsg             = "token generated successfully"
	ResponseResetPasswordMsg              = "password reset successfully"
	ResponseOkMsg                         = "ok"
	ResponseSendVerifyToEmailMsg          = "verify link has been sent to email"
	ResponseVerifiedMsg                   = "account verified successfully"
	ResponseUpdatePasswordMsg             = "password updated succesfully"
	ResponseUpdateApprovalAcceptedMsg     = "approval accepted succesfully"
	ResponseUpdateApprovalRejectedMsg     = "approval rejected succesfully"
	ResponseSendVerifyResetPassword       = "reset password link has been sent to email"
	ResponseGetDoctorSpecializations      = "get doctor specialization successfully"
	ResponseGetAllPendingDoctorApproval   = "get all doctor pending approval successfully"
	ResponseCategoryCreatedMsg            = "category created succesfully"
	ResponseCategoryUpdatedMsg            = "category updated succesfully"
	ResponseGetNewRefreshTokenMsg         = "successfully get new refresh token"
	ResponsePartnerUpdateMsg              = "partner updated succesfully"
	ResponseUpdateUserMsg                 = "user updated successfully"
	ResponseAddressCreatedMsg             = "address created successfully"
	ResponseAddressUpdatedMsg             = "address updated successfully"
	ResponseAddressDeletedMsg             = "address deleted successfully"
	ResponseCreateMessageMsg              = "message created succesfully"
	ResponseCreateChatRoomMsg             = "chat room created succesfully"
	ResponseGetAllMessageInOneChatRoomMsg = "succesfully get all message in one chat room"
	ResponseUpdateIsTypingMsg             = "successfully update is typing"
	ResponseGetAllChatRoomMsg             = "succesfully get all chat room"
	ResponseDeleteChatRoomMsg             = "succesfully delete a chat room"
	ResponseDeleteMessageMsg              = "succesfully delete a message"
	ResponseCartUpdatedMsg                = "cart updated successfully"
	ResponseCartCheckoutMsg               = "cart checkout successfully"
	ResponseCartItemDeletedMsg            = "cart item deleted successfully"
	ResponsePrescriptionCreatedMsg        = "prescription created successfully"
	ResponseSuccessUploadCloudinaryMsg    = "successfully upload to cloudinary"
	ResponsePharmacyProductCreatedMsg     = "pharmacy product created succesfully"
)
